version: 2

models:
  - name: energy
    description: normal test table

    columns:
      - name: row_id
        
      - name: energy_count 
        description: Customer's first name. PII.

      - name: row_id_100
        description: Customer's last name. PII.
